#
# DO NOT EDIT THIS FILE DIRECTLY - UNLESS YOU KNOW WHAT YOU ARE DOING
#

user node[:kzookeeper][:user] do
  action :create
  supports :manage_home => true
  home "/home/#{node[:kzookeeper][:user]}"
  shell "/bin/bash"
  not_if "getent passwd #{node[:kzookeeper]['user']}"
end

group node[:kzookeeper][:group] do
  action :modify
  members ["#{node[:kzookeeper][:user]}"]
  append true
end


# See ark resource here: https://github.com/burtlo/ark
# It will: fetch it to to /var/cache/chef/
# unpack it to the default path (/usr/local/XXX-1.2.3)
# create a symlink for :home_dir (/usr/local/XXX) 
# add /user/local/XXX/bin to the enviroment PATH variable
#  ark 'kzookeeper' do
#    url node[:kzookeeper][:url]
#    version node[:kzookeeper][:version]
#    path node[:kzookeeper][:version_dir]
#    home_dir node[:kzookeeper][:home_dir]
#    
#    append_env_path true
#    owner node[:kzookeeper][:user]
#  end

# bash "experiment_install_bash" do
#     user "root"
#     code <<-EOF
# Do something here...
# touch #{node[:kzookeeper][:version_dir]}/.installed
# EOF
#   not_if { ::File.exists?( "#{node[:kzookeeper][:version_dir]}/.installed" ) }
# end

#my_private_ip= my_private_ip()
#my_public_ip= my_public_ip()



# Pre-Experiment Code
include_recipe "zookeeper"
include_recipe "zookeeper::service"

zk_ip = private_cookbook_ip("zookeeper")

zookeeper_node "/kafka" do
  connect_str "#{zk_ip}:2181"
  data "some data"
end

# Configuration Files


